sudo: false
language: elixir
addons:
  apt:
    packages:
      - libtool
      - ghostscript
      - libgraphicsmagick1-dev
elixir:
  - 1.4
  - 1.5
  - 1.6
otp_release:
  - 20.0
  - 20.1
  - 20.2
  - 20.3
env:
  - exm_dirty_sched=no
  - exm_dirty_sched=auto
matrix:
  include:
    - elixir: 1.3
      otp_release: 19.0
      env: exm_dirty_sched=no
    - elixir: 1.3
      otp_release: 19.1
      env: exm_dirty_sched=no
    - elixir: 1.3
      otp_release: 19.2
      env: exm_dirty_sched=no
    - elixir: 1.3
      otp_release: 19.3
      env: exm_dirty_sched=no
