sudo: false
language: elixir
addons:
  apt:
    packages:
      - libtool
      - ghostscript
      - libgraphicsmagick1-dev
elixir:
  - 1.3
  - 1.4
  - 1.5
  - 1.6
otp_release:
  - 19.3
  - 20.0
  - 20.1
  - 20.2
  - 20.3
matrix:
  exclude:
    - elixir: 1.3
      otp_release: 20.0
    - elixir: 1.3
      otp_release: 20.1
    - elixir: 1.3
      otp_release: 20.2
    - elixir: 1.3
      otp_release: 20.3
